// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-rpGMX0McVoCXlHe4Xzig7yJM4lYesZM',
    appId: '1:949777069358:web:27e9e6b4fbd101ec7b36bf',
    messagingSenderId: '949777069358',
    projectId: 'floorbit-a3b55',
    authDomain: 'floorbit-a3b55.firebaseapp.com',
    storageBucket: 'floorbit-a3b55.firebasestorage.app',
    measurementId: 'G-4QV1HM23LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWcNltaZaWYY0uJAYUi86Rh9pWl3j9WWs',
    appId: '1:949777069358:android:c9084459184a941e7b36bf',
    messagingSenderId: '949777069358',
    projectId: 'floorbit-a3b55',
    storageBucket: 'floorbit-a3b55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8hQcg2BjvjQtg9gttERQ9W6bY1ZnpNIM',
    appId: '1:949777069358:ios:c6b08f8cbb64d9197b36bf',
    messagingSenderId: '949777069358',
    projectId: 'floorbit-a3b55',
    storageBucket: 'floorbit-a3b55.firebasestorage.app',
    iosBundleId: 'com.example.versioncopy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8hQcg2BjvjQtg9gttERQ9W6bY1ZnpNIM',
    appId: '1:949777069358:ios:c6b08f8cbb64d9197b36bf',
    messagingSenderId: '949777069358',
    projectId: 'floorbit-a3b55',
    storageBucket: 'floorbit-a3b55.firebasestorage.app',
    iosBundleId: 'com.example.versioncopy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-rpGMX0McVoCXlHe4Xzig7yJM4lYesZM',
    appId: '1:949777069358:web:8e44ab1effe1ea1e7b36bf',
    messagingSenderId: '949777069358',
    projectId: 'floorbit-a3b55',
    authDomain: 'floorbit-a3b55.firebaseapp.com',
    storageBucket: 'floorbit-a3b55.firebasestorage.app',
    measurementId: 'G-TJKT7VPDHK',
  );
}
